version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"    
    # environment:
    #   DBURL: postgres:5432
    #   DBNAME: library-app
    #   DBUSERNAME: postgres
    #   DBPASSWORD: postgres

    environment:
      DBURL: ep-rapid-smoke-a2zcyrhr.eu-central-1.pg.koyeb.app/
      DBNAME: koyebdb
      DBUSERNAME: koyeb-adm
      DBPASSWORD: npg_imSv4UqgDG1w

#   depends_on:
#      - postgres


  # postgres:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: library-app

#     koyeb-adm:npg_imSv4UqgDG1w@ep-rapid-smoke-a2zcyrhr.eu-central-1.pg.koyeb.app/koyebdb
